---
title: "UJ Regressions"
output: html_document
---

```{r}
suppressMessages(library(readxl))
suppressMessages(library(igraph))
suppressMessages(library(tidyverse))
suppressMessages(library(dplyr))
suppressMessages(library(ggplot2))
suppressMessages(library(ggraph))
suppressMessages(library(maps))
suppressMessages(library(lubridate))
suppressMessages(library(janitor))
suppressMessages(library(tibble))
suppressMessages(library(haven))
```

# UJ Dataset

```{r}
uj_raw = read_xlsx("Langer-Eason Database Clean.xlsx", sheet = 1)
uj_raw$`prosecuting state`[32] = "Germany"

uj_data = uj_raw[,c(4:5,14,19,26)]

# Recode States
uj_data[uj_data$`def nationality state` == "Nazi","def nationality state"] = "Germany"
uj_data[uj_data$`def nationality state` == "Congo_Brazzaville","def nationality state"] = "Congo"
uj_data[uj_data$`def nationality state` == "Congo_DRC","def nationality state"] = "Democratic Republic of the Congo"
uj_data[uj_data$`def nationality state` == "ISIS/Daesh","def nationality state"] = "Iraq" # Or Syria?
uj_data[uj_data$`def nationality state` == "The_Netherlands","def nationality state"] = "Netherlands"
uj_data[uj_data$`def nationality state` == "Former Yugoslavia","def nationality state"] = "Serbia" # Or Montenegro?
uj_data[uj_data$`def nationality state` == "Former_Yugoslavia","def nationality state"] = "Serbia" # Or Montenegro?

uj_data[uj_data$`prosecuting state` == "New_Zealand","prosecuting state"] = "New Zealand"
uj_data[uj_data$`prosecuting state` == "The_Netherlands","prosecuting state"] = "Netherlands"

uj_data = data.frame(uj_data)
uj_data$Initial_Trial_Start_Date = factor(uj_data$Initial_Trial_Start_Date)


states_data_clean1 = filter(uj_data, uj_data$Initial_Trial_Start_Date == "1989 (approx)")
states_data_clean2 = filter(uj_data, uj_data$Initial_Trial_Start_Date == "1990 (approx)")
states_data_clean3 = filter(uj_data, uj_data$Initial_Trial_Start_Date == "1994 (approx)")
states_data_clean4 = filter(uj_data, uj_data$Initial_Trial_Start_Date == "2005")
states_data_clean5 = filter(uj_data, uj_data$Initial_Trial_Start_Date == "NA")
states_data_clean6 = filter(uj_data, is.na(uj_data$Initial_Trial_Start_Date))
states_data_clean7 = filter(uj_data, !(uj_data$Initial_Trial_Start_Date == "1989 (approx)"|
                                       uj_data$Initial_Trial_Start_Date == "1990 (approx)" |
                                        uj_data$Initial_Trial_Start_Date == "1994 (approx)" |
                                        uj_data$Initial_Trial_Start_Date == "2005" |
                                        uj_data$Initial_Trial_Start_Date == "NA" |
                                        is.na(uj_data$Initial_Trial_Start_Date)))

states_data_clean1$TrialYear = 1989
states_data_clean2$TrialYear = 1990
states_data_clean3$TrialYear = 1994
states_data_clean4$TrialYear = 2005
states_data_clean5$TrialYear = NA
states_data_clean6$TrialYear = NA

states_data_clean7$Initial_Trial_Start_Date = excel_numeric_to_date(as.numeric(as.character(states_data_clean7$Initial_Trial_Start_Date)), date_system = "modern")    
states_data_clean7$TrialYear = as.numeric(substring(states_data_clean7$Initial_Trial_Start_Date,1,4))

states_data_clean7$Initial_Trial_Start_Date = as.character(states_data_clean7$Initial_Trial_Start_Date)

uj_data = bind_rows(states_data_clean1,states_data_clean2,states_data_clean3,states_data_clean4,states_data_clean5,states_data_clean6,states_data_clean7)
```

# DEMIG Dataset

```{r}
demig_data = read_excel("demig-c2c-migration-flow-database-version-1-2_limited-online-edition.xlsx", sheet = "Inflow")
```

# Replication Dataset

```{r}
replication_data = read_dta("Replication_Migration_Dyadic.dta")
```

# Leblang Dataset

```{r}
leblang_data = read_dta("updated_Migration_Data_08Jan15.dta")
```

# UNHCR Dataset

```{r}
unhcr_data = read.csv("imputed.csv")
```

# CCodes

```{r}
ccode = read_excel("COW-ISO-IMF country code lists.xlsx")
ccode = ccode[,c(2:3)]
ccode = distinct(ccode, CCode, .keep_all = T)
```

# UJ Data Aggregates by Country/Year

```{r}
def_table = uj_data %>% 
  group_by(`def.nationality.state`) %>% 
  summarise(`First Case` = min(`Case.Year`),
            `Total Cases` = sum(!is.na(Case.Year)),
            `Cases 1950 - 2000` = sum(!is.na(Case.Year) & Case.Year <= 2000),
            `Cases 2000 - Present` = sum(!is.na(Case.Year) & Case.Year > 2000),
            `First Trial` = suppressWarnings(min(`TrialYear`, na.rm=T)),
            `Total Trials` = sum(!(is.na(TrialYear))),
            `Trials 1950 - 2000` = sum(!is.na(TrialYear) & TrialYear <= 2000),
            `Trials 2000 - Present` = sum(!is.na(TrialYear) & TrialYear > 2000)) %>%
  mutate(`First Trial` = ifelse(is.infinite(`First Trial`), NA, `First Trial`))

pro_table = uj_data %>% 
  group_by(`prosecuting.state`) %>% 
  summarise(`First Case` = min(`Case.Year`),
            `Total Cases` = sum(!is.na(Case.Year)),
            `Cases 1950 - 2000` = sum(!is.na(Case.Year) & Case.Year <= 2000),
            `Cases 2000 - Present` = sum(!is.na(Case.Year) & Case.Year > 2000),
            `First Trial` = suppressWarnings(min(`TrialYear`, na.rm=T)),
            `Total Trials` = sum(!(is.na(TrialYear))),
            `Trials 1950 - 2000` = sum(!is.na(TrialYear) & TrialYear <= 2000),
            `Trials 2000 - Present` = sum(!is.na(TrialYear) & TrialYear > 2000)) %>%
  mutate(`First Trial` = ifelse(is.infinite(`First Trial`), NA, `First Trial`))
```

# Merge UJ Dataset with CCode

```{r}
pro_table[pro_table$prosecuting.state == "United States", "prosecuting.state"] = "United States of America"
pro_table = inner_join(pro_table,ccode,by = c("prosecuting.state" = "StateNme"))

def_table[def_table$def.nationality.state == "United States", "def.nationality.state"] = "United States of America"
def_table = inner_join(def_table,ccode,by = c("def.nationality.state" = "StateNme"))
```

# Merge UJ Dataset with Replication Data

```{r}
pro_data = uj_data %>% group_by(prosecuting.state, Case.Year) %>%
  summarise(count = n())
def_data = uj_data %>% group_by(def.nationality.state, Case.Year) %>%
  summarise(count = n())

pro_data = inner_join(pro_data,ccode,by = c("prosecuting.state" = "StateNme"))
def_data = inner_join(def_data,ccode,by = c("def.nationality.state" = "StateNme"))

colnames(pro_data)[3] = "prosecuting.count"
colnames(def_data)[3] = "defending.count"

merged_data = inner_join(replication_data,pro_data,by = c("ccode2" = "CCode", "year" = "Case.Year"))
merged_data = inner_join(merged_data,def_data,by = c("ccode1" = "CCode", "year" = "Case.Year"))
```

# Merge Leblang Data with CCode

```{r}
ccode = read_excel("COW-ISO-IMF country code lists.xlsx")
ccode = distinct(ccode, CCode, .keep_all = T)
ccode = ccode[,c(2,4)]

leblang_data = inner_join(leblang_data,ccode,by = c("iso_o" = "ISO"))
colnames(leblang_data)[7] = "ccode1"

leblang_data = inner_join(leblang_data,ccode,by = c("iso_d" = "ISO"))
colnames(leblang_data)[8] = "ccode2"
```

# Merge Leblang Data (Leblang + Replication + UJ)

```{r}
merged_data = inner_join(merged_data,leblang_data,by = c("ccode1" = "ccode1", "ccode2" = "ccode2", "year" = "year"))
```

# Split Demig Data

```{r}
demig_coc = demig_data[demig_data$Criterion == "COC",]
demig_cob = demig_data[demig_data$Criterion == "COB",]
demig_cor = demig_data[demig_data$Criterion == "COR",]

demig_coc = demig_coc[,c(1,16:18)]
demig_cob = demig_cob[,c(1,16:18)]
demig_cor = demig_cor[,c(1,16:18)]
```

# Rome Statute Data

```{r}
rome_data = read_xlsx("Data-Rome-Statute.xlsx")
```

# Merge Rome Statute

```{r}

```

